/**
 * Bundles the prompt sources (Markdown fragments, few-shot JSON, reference
 * sections) into prompts/bundle.ts, a plain TypeScript module, so the editor
 * (Vite), the proxy (tsx / Cloudflare Worker) and Node tests all load the same
 * text with no file-system or `?raw` loader.
 *
 *   npx tsx prompts/build.ts          # rewrite prompts/bundle.ts
 *   npx tsx prompts/build.ts --check  # exit 1 if bundle.ts is stale
 *
 * A test (apps/editor/src/fill/prompt.test.ts) fails when the bundle is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const PROMPTS_DIR = path.dirname(fileURLToPath(import.meta.url));
export const BUNDLE_PATH = path.join(PROMPTS_DIR, "bundle.ts");

/** Brief fragments, in the order they appear in the system prompt. */
export const BRIEF_ORDER = ["catalogue", "types", "styles", "placement", "variety", "fix"] as const;

const read = (...p: string[]) => readFileSync(path.join(PROMPTS_DIR, ...p), "utf8").replace(/\r\n/g, "\n");

/** The source text of prompts/bundle.ts for the files on disk. */
export function bundleSource(): string {
  const fill = read("fill.v1.md");
  const brief: Record<string, string> = {};
  for (const name of BRIEF_ORDER) brief[name] = read("brief", `${name}.md`);
  const shots = readdirSync(path.join(PROMPTS_DIR, "fewshot"))
    .filter((f) => f.endsWith(".json"))
    .sort((a, b) => parseInt(a) - parseInt(b) || a.localeCompare(b))
    .map((f) => JSON.parse(read("fewshot", f)));
  const refs = readdirSync(path.join(PROMPTS_DIR, "reference"))
    .filter((f) => f.endsWith(".txt"))
    .sort()
    .map((f) => ({ name: f.replace(/\.txt$/, ""), text: read("reference", f) }));
  return [
    "// GENERATED by prompts/build.ts from prompts/*.md, prompts/brief/*.md,",
    "// prompts/fewshot/*.json and prompts/reference/*.txt. Do not edit by hand:",
    "// edit the sources and run `npx tsx prompts/build.ts`.",
    'import type { FewShot } from "./fewshot/scenarios";',
    "",
    `export const FILL_PROMPT_V1: string = ${JSON.stringify(fill)};`,
    "",
    `export const BRIEF_FRAGMENTS: Readonly<Record<${BRIEF_ORDER.map((n) => JSON.stringify(n)).join(" | ")}, string>> = ${JSON.stringify(brief, null, 2)};`,
    "",
    `export const FEWSHOTS: readonly FewShot[] = ${JSON.stringify(shots, null, 1)};`,
    "",
    `export const REFERENCE_SECTIONS: readonly { name: string; text: string }[] = ${JSON.stringify(refs, null, 2)};`,
    "",
  ].join("\n");
}

export function writeBundle(): void {
  writeFileSync(BUNDLE_PATH, bundleSource());
}

export function bundleIsFresh(): boolean {
  try {
    return readFileSync(BUNDLE_PATH, "utf8") === bundleSource();
  } catch {
    return false;
  }
}

const invokedDirectly = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  if (process.argv.includes("--check")) {
    if (!bundleIsFresh()) {
      console.error("prompts/bundle.ts is stale: run npx tsx prompts/build.ts");
      process.exit(1);
    }
    console.log("prompts/bundle.ts is up to date");
  } else {
    writeBundle();
    console.log("wrote prompts/bundle.ts");
  }
}
