import { readFileSync } from "node:fs";
import { analyzeWindow, fullRect, measureLevel } from "@measure";
import { parseLevelSource, sourceToSnapshot } from "./lib/source";
const name = process.argv[2];
const s = sourceToSnapshot(parseLevelSource(readFileSync(`levels/src/${name}.txt`, "utf8"), `${name}.txt`));
const a = analyzeWindow(s, s.entities, fullRect(s));
console.log(a.patterns, a.hits.map(h=>`${h.tag}@${h.x0}-${h.x1}`).join(" "));
for (const t of a.graph.transitions) console.log(t.kind, t.from, t.to, "gap", t.gap, "dy", t.dy, "to", JSON.stringify(t.landing), "w", a.graph.surfaces[t.to].width, "d", a.graph.surfaces[t.to].depth, t.reachable);
const lm = measureLevel(s);
console.log(lm.series.patterns.map((p,i)=>i+":"+p.join(",")).join(" | "));
